name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows to run this via the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check which part is affected
        id: source-affected
        uses: dorny/paths-filter@v2
        with:
          filters: |
            device:
              - 'device/**'
            ui:
              - 'ui/**'

    outputs:
      deviceAffected: ${{ steps.source-affected.outputs.device }}
      uiAffected: ${{ steps.source-affected.outputs.ui }}

  ci-ui:
    needs: setup
    if: ${{ needs.setup.outputs.uiAffected == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: browser-actions/setup-chrome@latest

      - name: Install deps
        working-directory: ./ui
        run: npm install

      - name: Build the code
        working-directory: ./ui
        run: npm run build:ci

  ci-device:
    needs: setup
    if: ${{ needs.setup.outputs.deviceAffected == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - esp32dev
          - esp12e
          - esp01
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build the code
        working-directory: ./device
        run: pio run -e ${{ matrix.board }}
